# All modules
modules=example-app,\
        simple-map-app,\
        mapconductor-core,\
        mapconductor-icons,\
        mapconductor-marker-strategy,\
        mapconductor-marker-native-strategy,\
        mapconductor-marker-clustering,\
        mapconductor-heatmap,\
        mapconductor-tile-server,\
        mapconductor-bom,\
        mapconductor-for-here,\
        mapconductor-for-mapbox,\
        mapconductor-for-googlemaps,\
        mapconductor-for-arcgis,\
        mapconductor-for-maplibre
