//=In order to share the module names with gradle and KtLinter, define module names are below
modules=example-app,mapconductor-for-here,mapconductor-for-mapbox,mapconductor-for-googlemaps,mapconductor-for-arcgis,mapconductor-core,mapconductor-icons,mapconductor-marker-strategy,mapconductor-marker-native-strategy,mapconductor-bom
