# All modules
modules=example-app,\
        simple-map-app,\
        android-sdk-core,\
        android-sdk-compose,\
        android-icons,\
        android-marker-clustering,\
        android-heatmap,\
        android-geojson-layer,\
        mapconductor-bom,\
        android-for-here,\
        android-for-mapbox,\
        android-for-googlemaps,\
        android-for-arcgis,\
        android-for-maplibre,\
        android-geojson-layer
