[versions]
agp = "9.2.1"

core = "1.7.0"
kotlin = "2.4.0"

coreKtx = "1.19.0"
appcompat = "1.7.1"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
lifecycleViewmodelCompose = "2.10.0"

# https://developer.android.com/develop/ui/compose/bom/bom-mapping

# gradle.properties?kotlinCompilerExtensionVersion??????
compose = "1.11.2"
composeBom = "2026.05.01"
okhttp = "5.4.0"
runner = "1.7.0"

mapboxAndroid = "11.24.3"
playServicesMaps = "20.0.0"

arcgisMapsKotlin = "200.7.0"
vectordrawable = "1.2.0"
ktLint = "14.2.0"
geographiclib = "2.1"
mapLibreSdk = "13.3.0"
mapLibreAnnotation = "3.0.2"
runtime = "1.11.2"
runtimeVersion = "1.11.2"
materialVersion = "1.14.0"
jts = "1.20.0"
coroutines = "1.11.0"
uiGraphics = "1.11.2"
foundation = "1.11.2"

[libraries]
# Android ??
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Lifecycle / Activity Compose
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

# Jetpack Compose?with BOM?
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

mapconductor-core = { module = "com.mapconductor:core" }
mapconductor-icons = { module = "com.mapconductor:icons" }
mapconductor-googlemaps = { module = "com.mapconductor:for-googlemaps" }
mapconductor-mapbox = { module = "com.mapconductor:for-mapbox" }
mapconductor-here = { module = "com.mapconductor:for-here" }
mapconductor-arcgis = { module = "com.mapconductor:for-arcgis" }
mapconductor-maplibre = { module = "com.mapconductor:for-maplibre" }
mapconductor-marker-strategy = { module = "com.mapconductor:marker-strategy" }
mapconductor-marker-native-strategy = { module = "com.mapconductor:marker-native-strategy" }
mapconductor-marker-clustering = { module = "com.mapconductor:marker-clustering" }
mapconductor-geojson = { module = "com.mapconductor:geojson" }

# Mapbox
mapbox-android = { module = "com.mapbox.maps:android-ndk27", version.ref = "mapboxAndroid" }

# MapLibre
maplibre-sdk = { module = "org.maplibre.gl:android-sdk", version.ref = "mapLibreSdk" }
maplibre-annotation = { module = "org.maplibre.gl:android-plugin-annotation-v9", version.ref = "mapLibreAnnotation"}

# Google Maps
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }

# ArcGIS
arcgis-maps-kotlin = { group = "com.esri", name = "arcgis-maps-kotlin", version.ref = "arcgisMapsKotlin" }
arcgis-maps-kotlin-toolkit-bom = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-bom", version.ref = "arcgisMapsKotlin" }
arcgis-maps-kotlin-toolkit-geoview-compose = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-geoview-compose" }
arcgis-maps-kotlin-toolkit-authentication = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-authentication" }


# ????
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectordrawable" }

net-sf-geographiclib = { group = "net.sf.geographiclib", name="GeographicLib-Java", version.ref="geographiclib"}
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtimeVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
jts-core = { group = "org.locationtech.jts", name = "jts-core", version.ref = "jts" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jlleitschuh-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint"}
