[versions]
agp = "8.10.1"

core = "1.6.1"
kotlin = "2.0.21"

coreKtx = "1.15.0"
appcompat = "1.7.0"

junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"

lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
lifecycleViewmodelCompose = "2.9.0"

# https://developer.android.com/develop/ui/compose/bom/bom-mapping

# gradle.propertiesのkotlinCompilerExtensionVersionと一致させる
compose = "1.8.1"
composeBom = "2025.05.00"
runner = "1.6.2"

mapboxAndroid = "11.14.3"
playServicesMaps = "19.2.0"

secretsGradlePlugin = "2.0.1"

arcgisMapsKotlin = "200.7.0"
vectordrawable = "1.2.0"
firebaseBom = "34.2.0"
ktLint = "13.1.0"
uiToolingPreviewAndroid = "1.9.1"
uiToolingPreview = "1.9.1"
uiTooling = "1.9.1"
geographiclib = "2.1"

[libraries]
# Android 基本
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Lifecycle / Activity Compose
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

# Jetpack Compose（with BOM）
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

# Mapbox
mapconductor-core = { module = "com.mapconductor:core" }
mapconductor-icons = { module = "com.mapconductor:icons" }
mapconductor-googlemaps = { module = "com.mapconductor:for-googlemaps" }
mapconductor-mapbox = { module = "com.mapconductor:for-mapbox" }
mapconductor-here = { module = "com.mapconductor:for-here" }
mapconductor-arcgis = { module = "com.mapconductor:for-arcgis" }
mapconductor-marker-strategy = { module = "com.mapconductor:marker-strategy" }
mapconductor-marker-native-strategy = { module = "com.mapconductor:marker-native-strategy" }
mapbox-android = { module = "com.mapbox.maps:android-ndk27", version.ref = "mapboxAndroid" }

# Google Maps
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }

# ArcGIS
arcgis-maps-kotlin = { group = "com.esri", name = "arcgis-maps-kotlin", version.ref = "arcgisMapsKotlin" }
arcgis-maps-kotlin-toolkit-bom = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-bom", version.ref = "arcgisMapsKotlin" }
arcgis-maps-kotlin-toolkit-geoview-compose = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-geoview-compose" }
arcgis-maps-kotlin-toolkit-authentication = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-authentication" }

# テスト用
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectordrawable" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
androidx-compose-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

net-sf-geographiclib = { group = "net.sf.geographiclib", name="GeographicLib-Java", version.ref="geographiclib"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jlleitschuh-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint"}
