package com.mapconductor.vectorstyle

/**
 * The JNI surface of the vector style compiler.
 *
 * Owned by the `mapconductor-vectortile` repository and copied here by its
 * `scripts/sync-sdk.sh`. **Do not edit this file in the SDK**: the next sync
 * puts the upstream copy back, silently, and the change goes with it.
 *
 * Two calls, both JSON in and JSON out. The whole surface is this small
 * because the compiler holds no state -- a style and a rule set go in, an
 * adjusted style and the deltas come out -- so there is no handle to open or
 * free, and no thread the calls have to be made on.
 */
internal object NativeStyleCompiler {
    init {
        System.loadLibrary("mvt_style_jni")
    }

    /**
     * The compiled result as JSON: the adjusted style, the mutations, what
     * they affect and the diagnostics -- or `{"error": "..."}` when a
     * document could not be read.
     *
     * A document that cannot be read is answered, not thrown: a rule set
     * from a server or a style that failed to load is an ordinary thing to
     * handle, not an exceptional one. Only a panic becomes an exception.
     */
    external fun nativeCompile(
        styleJson: String,
        rulesJson: String,
    ): String

    /** The style's layers and the role each would be given, as a JSON array. */
    external fun nativeDescribe(styleJson: String): String

    /**
     * The rules document version this library understands.
     *
     * Read when the Kotlin side writes a rules document, so the two can
     * never disagree about the shape they are exchanging.
     */
    external fun nativeSchemaVersion(): Int
}
