[book]
title = "MapConductor Android SDK Documentation"
authors = ["MapConductor Team"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "build"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
additional-css = []
additional-js = []
print.enable = true
print.page-break = true
search.enable = true
search.limit-results = 30
search.teaser-word-count = 30
search.use-boolean-and = true
search.boost-title = 2
search.boost-hierarchy = 1
search.boost-paragraph = 1
search.expand = true
search.heading-split-level = 3
git-repository-url = ""
git-repository-icon = "fa-github"
edit-url-template = ""
site-url = ""
cname = ""

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = false
runnable = false